// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZeUvouZul-ukUSnMfDhPVby9tgamwnxc',
    appId: '1:201271697360:web:0e049d74b18cdf060c23d5',
    messagingSenderId: '201271697360',
    projectId: 'mini-social-network-c409e',
    authDomain: 'mini-social-network-c409e.firebaseapp.com',
    storageBucket: 'mini-social-network-c409e.firebasestorage.app',
    measurementId: 'G-KQH2P5MGZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWgrKoIUAEe7VBcW1gYQiJUTE_MzpZFv4',
    appId: '1:201271697360:android:27c0faaeab8da4780c23d5',
    messagingSenderId: '201271697360',
    projectId: 'mini-social-network-c409e',
    storageBucket: 'mini-social-network-c409e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbvvMoDHsv9sVlFqNykWGQuO3sf8We8fM',
    appId: '1:201271697360:ios:277f199367d251620c23d5',
    messagingSenderId: '201271697360',
    projectId: 'mini-social-network-c409e',
    storageBucket: 'mini-social-network-c409e.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbvvMoDHsv9sVlFqNykWGQuO3sf8We8fM',
    appId: '1:201271697360:ios:277f199367d251620c23d5',
    messagingSenderId: '201271697360',
    projectId: 'mini-social-network-c409e',
    storageBucket: 'mini-social-network-c409e.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZeUvouZul-ukUSnMfDhPVby9tgamwnxc',
    appId: '1:201271697360:web:4048c07477d06a290c23d5',
    messagingSenderId: '201271697360',
    projectId: 'mini-social-network-c409e',
    authDomain: 'mini-social-network-c409e.firebaseapp.com',
    storageBucket: 'mini-social-network-c409e.firebasestorage.app',
    measurementId: 'G-EC95X6V0QH',
  );
}
